### ISSUE TITLE
video quality?

### ISSUE THREAD

**Issue by Twapa** [gaeqs/JavaYoutubeDownloader#3]
how can i retrieve video quality without doing that automatically for me?

**Comment by gaeqs** [comment]
When you get the information from a video (Using JavaYoutubeDownloader.decode()) you're being returned all possible video options. If the quality you want it's not there, then youtube doesn't have it.

It's common that, on higher qualities, video and audio are splitted in two different streams. You must download both video and audio and then merge it. (You must use another API for that).
